/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SaSimulator {
    }
    interface SaSimulatorChart {
    }
    interface SaSimulatorForm {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSaSimulatorElement extends Components.SaSimulator, HTMLStencilElement {
    }
    var HTMLSaSimulatorElement: {
        prototype: HTMLSaSimulatorElement;
        new (): HTMLSaSimulatorElement;
    };
    interface HTMLSaSimulatorChartElement extends Components.SaSimulatorChart, HTMLStencilElement {
    }
    var HTMLSaSimulatorChartElement: {
        prototype: HTMLSaSimulatorChartElement;
        new (): HTMLSaSimulatorChartElement;
    };
    interface HTMLSaSimulatorFormElement extends Components.SaSimulatorForm, HTMLStencilElement {
    }
    var HTMLSaSimulatorFormElement: {
        prototype: HTMLSaSimulatorFormElement;
        new (): HTMLSaSimulatorFormElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sa-simulator": HTMLSaSimulatorElement;
        "sa-simulator-chart": HTMLSaSimulatorChartElement;
        "sa-simulator-form": HTMLSaSimulatorFormElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SaSimulator {
    }
    interface SaSimulatorChart {
    }
    interface SaSimulatorForm {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sa-simulator": SaSimulator;
        "sa-simulator-chart": SaSimulatorChart;
        "sa-simulator-form": SaSimulatorForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sa-simulator": LocalJSX.SaSimulator & JSXBase.HTMLAttributes<HTMLSaSimulatorElement>;
            "sa-simulator-chart": LocalJSX.SaSimulatorChart & JSXBase.HTMLAttributes<HTMLSaSimulatorChartElement>;
            "sa-simulator-form": LocalJSX.SaSimulatorForm & JSXBase.HTMLAttributes<HTMLSaSimulatorFormElement>;
        }
    }
}
